# Generated by Django 5.0.7 on 2024-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.CharField(max_length=255)),
                ('trades', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VolatilityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(unique=True)),
                ('iv_20', models.FloatField()),
                ('option_code', models.CharField(max_length=50)),
                ('option_price', models.FloatField()),
                ('option_delta', models.FloatField()),
                ('future_code', models.CharField(max_length=50)),
                ('future_price', models.FloatField()),
            ],
        ),
    ]
