# Generated by Django 5.0.7 on 2024-08-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_tradesession_volatilitydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeSession',
        ),
        migrations.DeleteModel(
            name='TradingData',
        ),
        migrations.AddField(
            model_name='volatilitydata',
            name='option_gamma',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='volatilitydata',
            name='option_theta',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='volatilitydata',
            name='option_vega',
            field=models.FloatField(default=0),
        ),
    ]
