# Generated by Django 5.0.7 on 2024-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_delete_tradesession_delete_tradingdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesOrderbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shcode', models.CharField(max_length=10)),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_volume', models.IntegerField()),
                ('ask_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ask_volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FuturesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shcode', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
