# Generated by Django 5.0.7 on 2024-09-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_futuresorderbook_futuresprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresprice',
            name='bidho1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='futuresprice',
            name='offerho1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
