# Generated by Django 5.0.7 on 2024-07-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='pnl',
            field=models.FloatField(default=0.0),
        ),
    ]
