# Generated by Django 5.0.7 on 2024-08-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_portfolio_pnl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('focode', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('volume', models.IntegerField()),
                ('multiplier', models.IntegerField(default=1)),
                ('direction', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_new', to='order.portfolio')),
            ],
        ),
    ]
