# Generated by Django 5.0.7 on 2024-08-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='trades',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='pnl',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
