# Generated by Django 5.0.7 on 2024-08-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_portfolio_pnl_alter_portfolio_portfolio_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='target_profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
