# Generated by Django 5.0.7 on 2024-08-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_update_trade_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
