# Generated by Django 5.0.7 on 2024-08-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_portfolio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='strategy',
            field=models.CharField(default='manual_order', max_length=50),
        ),
    ]
