# Generated by Django 5.0.7 on 2024-09-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_portfolio_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
