# Generated by Django 5.0.7 on 2024-09-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_portfolio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='liquidation_condition',
            field=models.CharField(blank=True, choices=[('pl', 'PL'), ('time', 'Time'), (None, 'None')], default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='liquidation_time_in_second',
            field=models.IntegerField(default=300),
        ),
    ]
