# Generated by Django 5.0.7 on 2024-09-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_portfolio_liquidation_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='liquidation_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
