# Generated by Django 5.0.7 on 2024-09-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_portfolio_liquidation_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='liquidation_time_in_second',
            field=models.IntegerField(blank=True, default=300, null=True),
        ),
    ]
