# Generated by Django 5.0.7 on 2024-09-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_portfolio_liquidation_time_in_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
