# Generated by Django 5.1.1 on 2024-10-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_trade_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='liquidation_condition',
            field=models.CharField(blank=True, choices=[('pl', 'PL'), ('time', 'Time'), ('pl_or_time', 'PL or Time'), (None, 'None')], default=None, max_length=10, null=True),
        ),
    ]
