DATE_FORMAT = "%Y-%m-%d"
DATETIME_FORMAT = "%Y-%m-%d %H%M%S"


DELTA_DIFFERENTIAL = 1.0e-3
VEGA_DIFFERENTIAL = 1.0e-2
GAMMA_DIFFERENTIAL = 1.0e-3
RHO_DIFFERENTIAL = 1.0e-4
THETA_DIFFERENTIAL = 1.0e-5

IMPLIED_VOLATILITY_TOLERANCE = 0.0005
SOLVER_STARTING_VALUE = 0.2

OVERNIGHT_RATE = 0
FALLBACK_RISK_FREE_RATE = 0.02

CD_RATE = 0.0383
